name: HaploHyped-VarAwareML
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - polars
  - h5py
  - numpy
  - pysam
  - hdf5plugin
  - cmake
  - make
  - gcc_linux-64
  - gxx_linux-64
  - htslib
  - pybind11
  - xz
  - zlib
  - gdb
  - pip
  - click
  - setuptools
  - pip:
    - b2h5py
